#spring.application.name=backend
server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/project-manager
#          jwk-set-uri: http://localhost:8080/realms/project-manager/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/projectmanager
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://localhost:8080
  realm: project-manager
  client_id: project-manager-client
  username: admin
  password: admin

file:
  upload-dir: C:/uploads/attachments