server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/project-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/projectmanager
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      write-dates-as-timestamps: false

keycloak:
  auth-server-url: http://localhost:8080
  target-realm: project-manager
  client-id: project_manager_client
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

logging:
  level:
    com.projectmanager: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.client: DEBUG
    root: INFO

minio:
  url: ${MINIO_URL:http://127.0.0.1:9000}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: project-manager-attachments

gemini:
  api-key: ${GEMINI_API_KEY}