#spring.application.name=backend
server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/project-manager
#          jwk-set-uri: http://localhost:8080/realms/project-manager/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/projectmanager
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://localhost:8080
  realm: project-manager
  client_id: project-manager-client
  client-secret: zvWp7DOJzI2V5HEFOgKCGG0y4xkX6sDg
  username: admin
  password: admin

#file:
#  upload-dir: C:/uploads/attachments
  #MinIO

minio:
  url: http://127.0.0.1:9000
  accessKey: biti
  secretKey: bitibiti
  bucketName: project-manager-attachments