#spring.application.name=backend
server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/projectmanager
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://localhost:8080
  target-realm: master
  client-id: admin-cli
  client-secret: JD2j1t7OTiHHU3glZoSrJcVcsKpzAorT
  username: admin
  password: admin

#file:
#  upload-dir: C:/uploads/attachments
  #MinIO

minio:
  url: http://127.0.0.1:9000
  accessKey: biti
  secretKey: bitibiti
  bucketName: project-manager-attachments